<?php

namespace Aurum\CrmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	/**
     * Retrieve
     *
     * @param integer $complaintId - Complaint Id
     *
     * @return Complaint
     */
    public function retrieve($userId)
    {
        $user =  $this->find($userId);

        return $user->serialise();
    }
}
